console.log(`Mohammad Hajeer - Feb 19 2025`)
console.log(`Hello`)

console.log(`Today is feburary 26 2025`)
console.log(`This is Eddie Maple Leaf 0226`)
console.log('Im here today')
console.log('Im here today')
console.log('Im here today')
console.log('Im here today')
console.log('Im here today')
console.log('Im here today')
console.log('Im here today')
console.log('Im here today')
console.log(`I am learning git`)